// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBayH4ZhXIo_kWt3fy7TyWoSpH0jx55l40',
    appId: '1:908004028183:web:3c3bd1a2a9f7b5e4d39152',
    messagingSenderId: '908004028183',
    projectId: 'flutter-test-be7b4',
    authDomain: 'flutter-test-be7b4.firebaseapp.com',
    storageBucket: 'flutter-test-be7b4.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBs-wAfy_XjQHxK1DB3LRDHWJJN_3jVmSw',
    appId: '1:908004028183:android:233a73775aee915cd39152',
    messagingSenderId: '908004028183',
    projectId: 'flutter-test-be7b4',
    storageBucket: 'flutter-test-be7b4.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA2O_F51PKMs59WP3Pb4no2cTBjn7tsnR4',
    appId: '1:908004028183:ios:675cf99787e0fa4dd39152',
    messagingSenderId: '908004028183',
    projectId: 'flutter-test-be7b4',
    storageBucket: 'flutter-test-be7b4.appspot.com',
    iosClientId: '908004028183-nqq76keiljptpufftju2nq3t5m5fkp7p.apps.googleusercontent.com',
    iosBundleId: 'com.example.firebaseCrud',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA2O_F51PKMs59WP3Pb4no2cTBjn7tsnR4',
    appId: '1:908004028183:ios:311b9b8fb45761e7d39152',
    messagingSenderId: '908004028183',
    projectId: 'flutter-test-be7b4',
    storageBucket: 'flutter-test-be7b4.appspot.com',
    iosClientId: '908004028183-9f35a5ur383v3mqcc31grh4jd5aq56s1.apps.googleusercontent.com',
    iosBundleId: 'com.example.firebaseCrud.RunnerTests',
  );
}
